### PR TITLE
Bot Generation first iteration

### PR DESCRIPTION
**Pull request by acedward**
@Mauriceac I've generated these files based on the documentation.

This should / replace link from https://doc.cotalker.com/docs/documentation/automation/admin_routine#stage-type-list

```
ccjs.md
fceach.md
fcifelse.md
fcsleep.md
fcswitchall.md
fcswitchone.md
nwbotv2v3.md
nwrequest.md
pbactionbutton.md
pbanswerchecker.md
pbchangestate.md
pbchanneladduser.md
pbchanneltotaskse.md
pbcleanchannel.md
pbcopysurvey.md
pbcreatechannel.md
pbcreateproperty.md
pbcreatetask.md
pbcreateuser.md
pbduplicatetask.md
pbeditablesurvey.md
pbemail.md
pbgetchannelmessages.md
pbgiphy.md
pbhidemessages.md
pbmessage.md
pbpayments.md
pbpdf.md
pbqrcode.md
pbscript.md
pbsendsurvey.md
pbtaskaddeditor.md
pbtemplate.md
pbupdatechannel.md
pbupdateproperty.md
pbupdatetask.md
pbupdateuser.md
```

### CODE REVIEW

**Comment by acedward** [comment]
```
	new file:   pbgooglecalendar.md
	new file:   pbwhatsapp.md
```

**Comment by Mauriceac** [comment]
# Too many files changed by accident trying to update the branch. SORRY.

**Comment by acedward** [comment]
what?!

**Comment by acedward** [comment]
BTW every file in docs/documentation/automation/bots/* is autogenerated - any changes will be lost

**Comment by acedward** [comment]
I'm still waiting on engineering for the release of PBWhatsApp and CCJS

**Comment by Mauriceac** [comment]
# Page Updates
- Routine Builder page revised and updated.
- Stage(step) types table completed with **name**, **description**, **key**, and **link**.
- Images updated added to showcase the latest version.

# Missing descriptions:
  - Action Button
  - Get Channel Messages
  - Duplicate Tasks
  - Payment (?)
  - Script
 
# PDF
PDF created with Chrome: _Only for reviewing purposes; not the actual appearance in the browser._
[Routine Builder _ Partner & Technical Consultants Documentation.pdf](https://github.com/Cotalker/documentation/files/6468252/Routine.Builder._.Partner.Technical.Consultants.Documentation.pdf)

**Comment by acedward** [comment]
All these bots are in production now

**Comment by Mauriceac** [comment]
# PDF PREVIEW:WhatsApp Integration Specs

[WhatsApp Integration _ Partner & Technical Consultants Documentation.pdf](https://github.com/Cotalker/documentation/files/6562887/WhatsApp.Integration._.Partner.Technical.Consultants.Documentation.pdf)

**Pull request merged**
