### PR TITLE
Multiple Choice Component, Subproperty filter

### LINKED ISSUE #56: Update Documentation with filter information
https://doc.cotalker.com/docs/documentation/admin/admin_survey#multiple-choice

Should explain how the filter works. 
Any questions, in the discussions thread
https://github.com/Cotalker/documentation/discussions/50

------------------------
Hola!

Quería saber si me podrían explicar un poco sobre el filtro de un multiple choice en un survey. Me gustaría saber si en la casilla de al lado, se configura la operación o si siempre sería "equal".

Les adjunto una imagen! 
Screen Shot 2021-04-08 at 13 57 54

_Originally posted by @ValeMP in https://github.com/Cotalker/documentation/discussions/50_

### LINKED ISSUE #156: Add property filter documentation.
@acedward el modo **subproperty** permite escoger subpropiedades de otro campo de tipo propiedad en el mismo formulario.

A modo de ejemplo tengo este selector de propiedades:
image

Y quisiera implementar otro selector que muestre las subpropiedades de la selección anterior:
image

Para ello se configura con el identifier de la pregunta que tiene la propiedad padre así como está en el ejemplo.

El resultado será este:
image

Saludos!

_Originally posted by @guillevalin in https://github.com/Cotalker/documentation/discussions/50#discussioncomment-710235_

### PR DESCRIPTION
**Pull request by Mauriceac**
- **Multiple Choice** component page completely revised and edited. The previous table was divided up into parts.
- Examples for "Subproperty" and "Subproperty-Channel" Filters added.
- An example for "subproperty-user" might be needed.
- Example for "List of Items" added.
- Further explanation for "API type" needed.
- Examples might be to long :(

closes #156
closes #56
﻿

### CODE REVIEW

**Comment by Mauriceac** [comment]
## PDF for preview purposes only; does not reflect the actual design of the page:

[Multiple Choice Component _ Partner & Technical Consultants Documentation.pdf](https://github.com/Cotalker/documentation/files/6556218/Multiple.Choice.Component._.Partner.Technical.Consultants.Documentation.pdf)

**Comment by Mauriceac** [comment]
# New Feature Update:

Screen Shot 2021-05-28 at 2 45 18 PM

**Comment by acedward** [comment]
Looks great!
Let's merge this!

**Comment by acedward** [comment]
technically this is not a new feature, so the what's new - isn't so new ! but let's publish it anyway

**Pull request merged**
