### PR TITLE
Chat in Task

### LINKED ISSUE #142: What's New: Chat on Tasks View
Screen Shot 2021-05-04 at 9 28 27 AM

# Chat

The same chat interface used on channel view will be available on tasks view

### PR DESCRIPTION
**Pull request by Mauriceac**
- New Feature blog: Chat in Task
- _Client > Tasks_ revised.

**¿Se puede publicar o hay que esperar?**
closes #142

## Blog Preview
Screen Shot 2021-05-10 at 16 58 48

## Documentation Preview (PDF)
[task-in-chat.pdf](https://github.com/Cotalker/documentation/files/6454960/task-in-chat.pdf)

### CODE REVIEW

**Comment by Mauriceac** [comment]
@acedward
Ok. I can't find this feature in "stage" or "dev" to take a screenshot myself. I'll try editing the photo in the meantime.

**Comment by Mauriceac** [comment]
Does this look legit?

chat00

**Comment by acedward** [comment]
image

**Comment by acedward** [comment]
> @acedward
> Ok. I can't find this feature in "stage" or "dev" to take a screenshot myself. I'll try editing the photo in the meantime.

It's still in development! We expect it by end of month.

**Comment by Mauriceac** [comment]
_Imagen para el "New Feature". (Acutalizada también en la documentación "Cotalker App > Tasks")_
update_chat-in-task

**Comment by Mauriceac** [comment]
# New Feature Preview
Screen Shot 2021-05-24 at 4 00 14 PM

# Documentation > Cotalker App > Tasks (preview)
Screen Shot 2021-05-24 at 4 00 49 PM

@rafaelwalter

**Review by rafaelwalter — APPROVED** [review]

**Pull request merged**
