### PR TITLE
New Features: WhatsApp Integration

### LINKED ISSUE #135: What's new: Whatsapp Integration
Cotalker can now send messages through Whatsapp.

This can be done through the new step "Whatsapp Integration" 
Requirements: Full intl. phone e.g., +56123456789, link and workflow name.

*NOTE* This service has an additional cost per message. 
Contact your Cotalker Representative to get started.

### LINKED ISSUE #136: What's New: Google Workspace - Calendar Integration
Though a new Step-Bot now Cotalker can be integrated deeply into Google Calendar.
This integration allows to create meetings for any user, and invite any number of external people - only their emails are required

NOTE: This is a company wide integration - google workspace is required.

### PR DESCRIPTION
**Pull request by Mauriceac**
Two New Feature Updates:
- WhatsApp
- Google Calendar

closes #135

### CODE REVIEW

**Comment by Mauriceac** [comment]
# "New Feature" Preview

Screen Shot 2021-05-17 at 14 28 20

**Comment by Mauriceac** [comment]
# Questions:
In the comment above: 
- Is "**link**" the same as the "**contract code**" mentioned in the bot documentation?
- Is "**workflow name**" the same as "**template name**" mentioned in the bot documentation?

------

# "New Features" Preview

Screen Shot 2021-05-17 at 11 54 12

**Comment by acedward** [comment]
## Inputs  
### 1. Contract code (key: contractCode)  
The code can be found in the contract addendum: 'Whatsapp and SMS Integrations'  
Required: true  
Data Type: string   
### 2. Phone Number (key: phoneNumber)  
Full international number e.g., +56912345678  
Required: true  
Data Type: string   
### 3. template  
@Mauriceac  Whats Up only allows to send TEMPLATES as first message. We cannot create new ones on the fly, they have to be approved by facebook. So this is the name of the TEMPLATE to use. For now we only have "DEFAULT"

Use 'default'  
Required: true  
Data Type: string   
### 4. language  
'en' or 'es'  
Required: true  
Data Type: string   
### 5. Name (key: name)  
Name for template                                   
Required: true  
Data Type: string   
### 6. first  
@Mauriceac This is the first argument where "WORKFLOW NAME" should go, for TEMPLATE=default 

Template first argument  
Required: true  
Data Type: string   
### 7. second  
@Mauriceac  This is the second argument where "LINK" should go, only for TEMPLATE=default

Template second argument  
Required: true  
Data Type: string   
## Next Stages

**Comment by Mauriceac** [comment]
# PDF PREVIEW: WhatsApp Integration Specs

[Uploading WhatsApp Integration _ Partner & Technical Consultants Documentation.pdf…]()

**Comment by acedward** [comment]
I cant download the pdf

**Review by acedward — APPROVED** [review]
The PDF does not match the changes?

**Comment by Mauriceac** [comment]
> The PDF does not match the changes?

I don't understand.
???

**Comment by Mauriceac** [comment]
Oh! Now I understand. I haven't push the changes yet.
I think I'll have to make a new branch.

**Comment by acedward** [comment]
Or just merge these changes

**Pull request merged**
