### PR TITLE
Update Tree Selector

### LINKED ISSUE #7: What's new: Tree Selector
The new property - tree selector is available in development environments.
Please add this to what's new and to the survey-property section.
@Mauriceac @gmoplaza @rafaelwalter

### PR DESCRIPTION
**Pull request by Mauriceac**
- Added to "Updates"
- Added to Documentation > Admin > Survey:
  - **Hierarchy selection** added in **Multiple Choice** fields table.
  - **Tree Selector** section added to explain details and setup.

closes #7

### CODE REVIEW

**Comment by acedward** [comment]
ou can add "closes #34 " in the description, so when this PR is merged, the issues is also closed automatically

**Comment by acedward** [comment]
"Activate the Hierarchy selection option" 
I'm not sure about this - I had to setup the dependencies (sub-properties) manually to get this working

**Comment by Mauriceac** [comment]
I think I tried explaining that in the "Pre-Requisites" info box.

**Comment by acedward** [comment]
My bad, I read something wrong!

**Comment by Mauriceac** [comment]
Go to sleep!

**Pull request merged**
