### PR TITLE
Triggers and contexts page created, Quick Reference Guide embedded in Cotlang page

### LINKED ISSUE #105: Update COTLang & Move Triggers & Context
Now that we have the trigger & context list (https://doc.cotalker.com/docs/documentation/automation/admin_cotlang)
we should move it to Documentation >  Automation > Triggers & Contexts

And the COTLang secition can embed in an iframe the site https://www.cotalker.com/function/cotlang/
@Mauriceac can you check if docusaurus allow iframes? 

Something like this
```
<iframe className="batata" src="https://www.cotalker.com/function/cotlang/">
</iframe>
```

### PR DESCRIPTION
**Pull request by Mauriceac**
- Triggers & Contexts moved to Automations.
- https://www.cotalker.com/function/cotlang/ has been embedded with <iframe> in Cotlang.md
- But, horizontal bar NOT functioning.﻿

closes #105

### CODE REVIEW

**Comment by acedward** [comment]
@Mauriceac is it usable?

**Comment by Mauriceac** [comment]
Not really. For some reason, the original doesn't even create a horizontal bar when the window is narrowed.

**Comment by Mauriceac** [comment]
## Original Page isn't responsive nor allows horizontal bar.
Screen Shot 2021-04-23 at 15 09 32

## Here's the page embedded in the documentation. Only the tables get affected.
Screen Shot 2021-04-23 at 15 09 08

**Comment by acedward** [comment]
perhaps forcing the scrolling:
```
style="overflow-x: scroll;"
```

We should also move:
` ## Context language description {#context-language}` 
This is how to 'interpret' the context description

**Comment by Mauriceac** [comment]
## 1 Scrolling Quick Reference Guide
I tried "overflow-x: scroll" with no luck. 
Other web pages scrolled successfully. 
I believe the problem is with https://www.cotalker.com/function/cotlang/
On its own, it doesn't scroll either.

## Context Language Description
Does it have its own page or inserted in the Contexts & Triggers?

**Comment by acedward** [comment]
@Mauriceac OK we will update that site

**Comment by acedward** [comment]
@Mauriceac https://www.cotalker.com/function/cotlang/ was updated to work as expected

**Review by acedward — APPROVED** [review]

**Pull request merged**
