### PR TITLE
Revert "Contexts Update"

### PR DESCRIPTION
**Pull request by Mauriceac**
Reverts Cotalker/documentation#52

ERROR:

> Run npm run build
> 
> > cotalker@0.0.0 build /home/runner/work/documentation/documentation
> > docusaurus build
> 
> 
> [en] Creating an optimized production build...
> [Local Search] [INFO]: The documentation is not versioned (/home/runner/work/documentation/documentation/versions.json does not exist).
> [info] [webpackbar] Compiling Client
> [info] [webpackbar] Compiling Server
> [success] [webpackbar] Client: Compiled with some errors in 1.06m
> 
> 
> ./docs/documentation/automation/admin_cotlang.md
> SyntaxError: /home/runner/work/documentation/documentation/docs/documentation/automation/admin_cotlang.md: Expected corresponding JSX closing tag for <br> (25:155)
> ./docs/documentation/automation/admin_cotlang.md
> Module build failed (from ./node_modules/@docusaurus/mdx-loader/src/index.js):
> SyntaxError: /home/runner/work/documentation/documentation/docs/documentation/automation/admin_cotlang.md: Expected corresponding JSX closing tag for <br> (25:155)
> 
>   23 | <tr parentName="tbody">
>   24 | <td parentName="tr" {...{"align":null}}>{`Global Message Trigger`}</td>
> > 25 | <td parentName="tr" {...{"align":null}}><pre>{`{`}<br>{`  channel: COTChannel,`}<br>{`  message: COTMessage,`}<br>{`  cmdArgs: Array`}{`[string]`}<br>{`}`}</pre></td>
>      |                                                                                                                                                            ^
>   26 | <td parentName="tr" {...{"align":null}}>{`The source is a global bot that is trigger with a slash command.`}</td>
>   27 | </tr>
>   28 | <tr parentName="tbody">
>     at Object._raise (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:775:17)
>     at Object.raiseWithData (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:768:17)
>     at Object.raise (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:736:17)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5135:16)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElementAt (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5103:32)
>     at Object.jsxParseElement (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5161:17)
>     at Object.parseExprAtom (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:5168:19)
>     at Object.parseExprSubscripts (/home/runner/work/documentation/documentation/node_modules/@babel/parser/lib/index.js:10668:23)
>  @ ./.docusaurus/registry.js 1:19345-19420 1:19191-19287
>  @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
>  @ ./.docusaurus/routes.js
>  @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
>  @ multi ./node_modules/@docusaurus/core/lib/client/clientEntry.js
> 
>   23 | <tr parentName="tbody">
>   24 | <td parentName="tr" {...{"align":null}}>{`Global Message Trigger`}</td>
> > 25 | <td parentName="tr" {...{"align":null}}><pre>{`{`}<br>{`  channel: COTChannel,`}<br>{`  message: COTMessage,`}<br>{`  cmdArgs: Array`}{`[string]`}<br>{`}`}</pre></td>
>      |                                                                                                                                                            ^
>   26 | <td parentName="tr" {...{"align":null}}>{`The source is a global bot that is trigger with a slash command.`}</td>
>   27 | </tr>
>   28 | <tr parentName="tbody">
>  @ ./.docusaurus/registry.js 1:19345-19420 1:19191-19287
>  @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
>  @ ./.docusaurus/routes.js
>  @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
>  @ multi ./node_modules/@docusaurus/core/lib/client/clientEntry.js
> Client bundle compiled with errors therefore further build is impossible.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cotalker@0.0.0 build: `docusaurus build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the cotalker@0.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/runner/.npm/_logs/2021-04-08T20_18_49_952Z-debug.log
> Error: Process completed with exit code 1.

### CODE REVIEW

**Comment by Mauriceac** [comment]
This also breaks the build. I'll fix it as soon as I have the other revert done.

**Comment by Mauriceac** [comment]
**Note:**

`<pre>` & `<br/>` can't be used in _markdown_ table along with '{ }' characters, but can be used separately with them.

**Here are some alternatives for making the table:**
_(Tell me which one you like best, and configure the table you made to that format.)_

## Example 1 - using `<pre></pre>`
Screen Shot 2021-04-09 at 11 04 46

## Example 2 - using `<br/>`
Screen Shot 2021-04-09 at 11 08 33

## Example 3 - New table format!
Screen Shot 2021-04-09 at 11 08 16

**Comment by acedward** [comment]
@Mauriceac I think your third option is the best!
Tables don't scale well in smaller screens.
Can I ask you to do the rewrite?

**Comment by Mauriceac** [comment]
Great! I was waiting for you to choose the third one!
I got the idea from an IBM page.

**Comment by acedward** [comment]
@Mauriceac do we delete this PR or merge?

**Comment by Mauriceac** [comment]
I'm not done rewriting it.
I'll have it ready for merging before Wednesday.

**Comment by acedward** [comment]
I was asking, because this is a "Revert" PR.
These PRs just contains the commit to revert another pull-request.
So this can be merged ( to fix the PR #52 ) or deleted if not required.

**Pull request closed without merging**
